#server setting
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
    datasource:
        url: jdbc:mysql://182.92.216.144:3306/train_master?characterEncoding=utf8&serverTimezone=GMT%2B8
        #url: jdbc:mysql://182.92.216.144:3306/train_master
        username: chain
        password: xiangyanniqiu_82
    jpa:
        database: MYSQL
        show-sql: true
    #Hibernate ddl auto (validate|create|create-drop|update)
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                #默认创建的表的引擎是 MyISAM
                #dialect:org.hibernate.dialect.MySQL5Dialect
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
